#!/bin/bash
# file: dracut/92uaa-unlock-deadline/module-setup.sh
# version: 1.0.0
# guid: 8b2f6d14-0e77-4a3c-9d51-6f4c8a2b7e93
# last-edited: 2026-08-03
#
# BOUNDS THE INITRAMFS. Ships a drop-in that puts a hard deadline on the
# whole initrd, with a REBOOT as the action.
#
# WHY (all measured in the root-LUKS gate VM on U0, 2026-08-03; see
# docs/research/2026-08-03-clevis-initramfs-bounded-failclosed.md):
#
#   A clevis unlock that cannot be satisfied does not FAIL. systemd sits on an
#   ask-password query, contentedly, forever. Nothing enters an error path, so
#   every "action" knob (rd.emergency, systemd.crash_reboot, panic=) has
#   nothing to fire on. The console literally prints the reason:
#
#       (1 of 3) Job dracut-initqueue.service/start running (36s / no limit)
#
#   `systemctl show dracut-initqueue.service` reports TimeoutStartUSec=infinity
#   and JobTimeoutUSec=infinity. The clevis PIN prompt runs INSIDE that job
#   (the 50clevis-pin-pkcs11 dracut hooks), not inside
#   systemd-cryptsetup@root.service — which is why `crypttab timeout=`,
#   `rd.luks.options=timeout=` and `x-systemd.device-timeout=` govern the wrong
#   unit and bounded nothing (a 902 s hang was measured with both set).
#
#   So the deadline is attached to initrd.target's JOB: that job stays queued
#   until every initrd unit finishes, so one knob covers a hang anywhere in the
#   initramfs -- the clevis PIN prompt, the plain passphrase fallback, or a
#   device that never appears.
#
# ON A HOST WITH NO REMOTE POWER the action must be reboot, never a shell:
# Tang may simply have come back, and an unattended retry is the only thing
# that helps. reboot-force is also FAIL-CLOSED -- it resets the machine, it can
# never fall through to an unlocked or degraded boot.
#
# REQUIRED COMPANION on the kernel cmdline:  rd.shell=0 rd.emergency=reboot
#   Without rd.shell=0, dracut's emergency shell can pre-empt this deadline:
#   measured run B3 dropped to "Press Enter for system maintenance" at ~304 s
#   and the 600 s job deadline then never fired, because emergency.target
#   cancels the initrd.target job. With rd.shell=0 the same scenario rebooted
#   on schedule (run B4: "Forcibly rebooting: job timed out, proceeding in 5s"
#   -> "reboot: Restarting system" at 909.7 s, then the next boot re-armed the
#   PIN prompt -- an unattended retry loop).
#
# HONEST LIMITATION: JobTimeoutSec is a fixed wall clock measured from the
# initrd.target job start. It CANNOT be reset by "a human is typing". It will
# fire on someone who walks up at minute 9 and types slowly. The consequence is
# a reboot and a fresh prompt about a minute later, not a lockout -- which is
# why the value is sized generously rather than made adaptive. See the research
# doc for the alternatives that were considered and rejected.

# Deadline in seconds. Override from dracut.conf.d with
#   uaa_unlock_deadline_sec=900
# See the research doc for why 600 is the default.
: "${uaa_unlock_deadline_sec:=600}"

# dracut hook: decide whether to include this module.
check() {
    # No host prerequisites -- a deadline is useful on any encrypted root.
    # Included only when explicitly listed in add_dracutmodules.
    return 255
}

# dracut hook: module dependencies.
depends() {
    # The drop-in is only meaningful in a systemd-driven initramfs; without
    # systemd there is no initrd.target and no job to time out.
    echo systemd
    return 0
}

# dracut hook: write the drop-in straight into the initramfs.
install() {
    local dir="${initdir}/usr/lib/systemd/system/initrd.target.d"
    mkdir -p "$dir"
    cat > "${dir}/10-uaa-unlock-deadline.conf" <<EOF
# Generated by dracut/92uaa-unlock-deadline. Do not edit in the initramfs.
#
# JobTimeoutAction=reboot-force is a hard reset (no unmount, no shutdown
# transaction) -- correct here, because at this point the real root is not
# mounted and there is nothing to flush.
[Unit]
JobTimeoutSec=${uaa_unlock_deadline_sec}
JobTimeoutAction=reboot-force
EOF
    return 0
}
